---
- hosts: localhost
  roles:
    - andrewrothstein.proxify
    - andrewrothstein.julia
    - andrewrothstein.python
    - { role: 'andrewrothstein.anaconda', anaconda_make_sys_default : True }
    - andrewrothstein.node-n