---
- hosts: localhost
  roles:
    - andrewrothstein.proxify
    - {
    role: 'andrewrothstein.julia',
    julia_use_pkgs : False,
    julia_build_src : True,
    julia_build_repo : 'git://github.com/mdcfrancis/julia.git',
    julia_build_branch : 'mdf_verbose_precompile'
    }
    - andrewrothstein.python
    - { role: 'andrewrothstein.anaconda', anaconda_make_sys_default : True }
    - andrewrothstein.node-n
    - andrewrothstein.r